export const SITE = {
  name: 'EasyReimburse',
  tagline: 'AI-Powered Travel Reimbursement for Erasmus+',
  url: 'https://easyreimburse.ai',
  appUrl: 'https://app.easyreimburse.ai',
  registerUrl: 'https://app.easyreimburse.ai/org/register',
  loginUrl: 'https://app.easyreimburse.ai/org/login',
  contactEmail: 'contact@easyreimburse.ai',
  description:
    'Automate travel reimbursement for Erasmus+ youth mobility projects. AI-powered document processing. From weeks to minutes.',
} as const;

export const NAV_LINKS = [
  { label: 'Features', href: '/features' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'How It Works', href: '/how-it-works' },
  { label: 'Contact', href: '/contact' },
] as const;

export const PRICING_PLANS = [
  {
    name: 'Free',
    price: 0,
    unit: null,
    perProject: null,
    description: 'Perfect for trying EasyReimburse',
    features: [
      'Up to 10 participants',
      '1 project',
      'AI document processing',
      'Organisation dashboard',
    ],
    cta: 'Try for Free',
    ctaHref: SITE.registerUrl,
    highlighted: false,
    badge: null,
  },
  {
    name: 'Single Project',
    price: 129,
    unit: '/project',
    perProject: null,
    description: 'For a single mobility project',
    features: [
      'Up to 60 participants',
      '1 project credit',
      'AI document processing',
      'Organisation dashboard',
      'One-click NA Audit',
      'Email support',
    ],
    cta: 'Get Started',
    ctaHref: 'https://app.easyreimburse.ai/org/register?plan=SINGLE',
    highlighted: true,
    badge: 'Popular',
  },
  {
    name: '5-Pack',
    price: 499,
    unit: null,
    perProject: 99.8,
    description: 'For organizations running multiple projects',
    features: [
      'Up to 60 participants p/project',
      '5 project credits',
      'AI document processing',
      'Organisation dashboard',
      'One-click NA Audit',
      'Priority support',
    ],
    cta: 'Get Started',
    ctaHref: 'https://app.easyreimburse.ai/org/register?plan=PACK_5',
    highlighted: false,
    badge: null,
  },
  {
    name: '10-Pack',
    price: 899,
    unit: null,
    perProject: 89.9,
    description: 'Maximum savings for active organisations',
    features: [
      'Up to 60 participants p/project',
      '10 project credits',
      'AI document processing',
      'Organisation dashboard',
      'One-click NA Audit',
      'Priority support',
    ],
    cta: 'Get Started',
    ctaHref: 'https://app.easyreimburse.ai/org/register?plan=PACK_10',
    highlighted: false,
    badge: 'Best Value',
  },
] as const;

export const IMAGES = {
  hero: '/hero-rotterdam.png',
  features: '/features-rome.png',
  pricing: '/pricing-brussels.png',
  howItWorks: '/extra-neuschwanstein.png',
  contact: '/contact-prague.png',
  travel: '/travel-bled.png',
  cta: '/cta-athens.png',
} as const;
